# Generated by Django 3.1.7 on 2021-03-31 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTrade',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer', models.CharField(max_length=63)),
                ('seller', models.CharField(max_length=63)),
                ('amount', models.PositiveIntegerField()),
                ('rate', models.IntegerField()),
                ('buyer_public', models.BooleanField(default=False)),
                ('seller_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_escrows', models.IntegerField()),
                ('total_coins', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
