# Generated by Django 3.1.7 on 2021-03-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtrade',
            name='agent',
            field=models.CharField(default='hussu#9966', max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedtrade',
            name='agent_public',
            field=models.BooleanField(default=False),
        ),
    ]
