# Generated by Django 2.2.4 on 2021-04-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20210331_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='total_transactions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
