# Generated by Django 3.1.7 on 2021-03-31 03:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20210331_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtrade',
            name='id',
        ),
        migrations.AddField(
            model_name='completedtrade',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
