# Generated by Django 3.1.7 on 2021-04-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_statistic_total_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_escrows', models.IntegerField()),
                ('total_coins', models.IntegerField()),
                ('total_transactions', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
