# Generated by Django 3.1.7 on 2021-03-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_auto_20210331_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_escrows', models.IntegerField()),
                ('total_coins', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
