# Generated by Django 3.1.7 on 2021-04-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_backupstatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=64)),
            ],
        ),
    ]
