# Generated by Django 3.1.7 on 2021-03-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtrade',
            name='buyer_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='completedtrade',
            name='seller_public',
            field=models.BooleanField(default=False),
        ),
    ]
