# Generated by Django 3.1.7 on 2021-04-22 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_blacklistedwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistedwallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blacklistedwallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
