# Generated by Django 3.2 on 2021-04-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_auto_20210422_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
