# Generated by Django 3.2 on 2021-05-08 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtrade',
            name='escrower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trades.agent'),
            preserve_default=False,
        ),
    ]
