# Generated by Django 3.2 on 2021-05-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0010_completedtrade_escrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtrade',
            name='agent',
        ),
    ]
