# Generated by Django 3.2 on 2021-05-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0011_remove_completedtrade_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedtrade',
            old_name='escrower',
            new_name='agent',
        ),
    ]
