# Generated by Django 3.2 on 2021-06-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0012_rename_escrower_completedtrade_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='circulating_supply',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='max_supply',
            field=models.IntegerField(default=0),
        ),
    ]
