# Generated by Django 3.2 on 2021-10-19 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0013_auto_20210606_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerageOffer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid_hex', models.CharField(max_length=255, unique=True)),
                ('amount', models.IntegerField()),
                ('executed', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('total', models.IntegerField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('FILLED', 'Filled'), ('PARTIALLY_FILLED', 'Partially Filled'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=255)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
