# Generated by Django 3.2 on 2021-11-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0014_brokerageoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='api_key',
            field=models.CharField(default='test-key', max_length=255),
            preserve_default=False,
        ),
    ]
