# Generated by Django 3.2.9 on 2021-11-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0015_statistic_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtrade',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trades.agent'),
        ),
        migrations.AlterField(
            model_name='completedtrade',
            name='buyer',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='completedtrade',
            name='seller',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
